# Generated by Django 5.0.6 on 2024-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
